version: 2.1
orbs:
    samvera: samvera/circleci-orb@dev:optional-gemspec
jobs:
    install_and_test:
        parameters:
            ruby_version:
                type: string
                default: 2.5.3
            bundler_version:
                type: string
                default: 2.0.1
        executor:
            name: samvera/ruby_fcrepo_solr_redis
            ruby_version: << parameters.ruby_version >>
        working_directory: ~/project
        parallelism: 4
        steps:
            - checkout

            - samvera/bundle_for_gem:
                ruby_version: << parameters.ruby_version >>
                bundler_version: << parameters.bundler_version >>
                project: none
                require_gemspec: false

            - samvera/rubocop

            - samvera/install_solr_core

            #- run:
            #    command: |
            #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            #       chmod +x ./cc-test-reporter
            #       ./cc-test-reporter before-build

            - samvera/parallel_rspec

            #- run:
            #    command: ./cc-test-reporter after-build -t simplecov --exit-code $?

workflows:
    ci:
        jobs:
            - install_and_test:
                name: ruby2-5-3
            #- install_and_test:
            #    name: ruby2-6-3
            #    ruby_version: 2.6.3
